name: CI & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: '22.x'

jobs:
  ci:
    name: Lint, Type Check, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure npm peer deps
        run: |
          npm config set legacy-peer-deps true

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --silent || true

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

  deploy:
    name: Deploy to Vercel (Preview)
    needs: [ ci ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.vercel.outputs.preview-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure npm peer deps
        run: |
          npm config set legacy-peer-deps true

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy with Vercel (preview)
        id: vercel
        uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          prod: false
        env:
          # Runtime secrets used by Next.js build/server
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLAUDE_MODEL: ${{ secrets.CLAUDE_MODEL }}
          CLAUDE_MAX_TOKENS: ${{ secrets.CLAUDE_MAX_TOKENS }}
          CLAUDE_TEMPERATURE: ${{ secrets.CLAUDE_TEMPERATURE }}
          OPENAI_EMBEDDING_MODEL: ${{ secrets.OPENAI_EMBEDDING_MODEL }}
          AI_REQUEST_TIMEOUT_MS: ${{ secrets.AI_REQUEST_TIMEOUT_MS }}
          # BOLAGSVERKET removed

      - name: Output preview URL
        run: |
          echo "Deployment URL: ${{ steps.vercel.outputs.preview-url }}"

      - name: Comment preview URL on commit
        if: ${{ steps.vercel.outputs.preview-url != '' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = core.getInput('url') || `${{ steps.vercel.outputs.preview-url }}`;
            const sha = process.env.GITHUB_SHA;
            await github.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha,
              body: `🧪 Preview deployed: ${url}`
            });

