name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLAUDE_MODEL: ${{ secrets.CLAUDE_MODEL }}
          CLAUDE_MAX_TOKENS: ${{ secrets.CLAUDE_MAX_TOKENS }}
          CLAUDE_TEMPERATURE: ${{ secrets.CLAUDE_TEMPERATURE }}
          OPENAI_EMBEDDING_MODEL: ${{ secrets.OPENAI_EMBEDDING_MODEL }}
          AI_REQUEST_TIMEOUT_MS: ${{ secrets.AI_REQUEST_TIMEOUT_MS }}
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLAUDE_MODEL: ${{ secrets.CLAUDE_MODEL }}
          CLAUDE_MAX_TOKENS: ${{ secrets.CLAUDE_MAX_TOKENS }}
          CLAUDE_TEMPERATURE: ${{ secrets.CLAUDE_TEMPERATURE }}
          OPENAI_EMBEDDING_MODEL: ${{ secrets.OPENAI_EMBEDDING_MODEL }}
          AI_REQUEST_TIMEOUT_MS: ${{ secrets.AI_REQUEST_TIMEOUT_MS }}
      
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "deployment-url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          echo "🚀 Deployed to: $DEPLOYMENT_URL"
      
      - name: Comment deployment URL
        if: steps.deploy.outputs.deployment-url != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = `${{ steps.deploy.outputs.deployment-url }}`;
            const sha = process.env.GITHUB_SHA;
            await github.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha,
              body: `🚀 Deployed to Vercel: ${url}`
            });